services:
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 30
  auth-service:
    image: auth-service:1.0.0
    container_name: auth_service
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
      - "3001:8081"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ExternalPorts=3000,3001
      - ServerName=auth-server
      - JWTSecretToken=auth-server
      - DBUser=root
      - DBPass=example
      - DBAddr=db:3306
      - DBName=goauthservice
