openapi: 3.0.3
info:
  title: GoAuthService - OpenAPI 3.0
  version: 1.0.1
  description: |-
    An open-source authorization micro-service with SSO support.
  contact:
    email: inquire@keeganbruer.com
externalDocs:
  description: View Github
  url: https://github.com/KeeganBruer/GoAuthService
servers:
  - url: http://localhost:3000/
tags:
  - name: user
    description: Operations about user
paths:
  /login:
    post:
      tags:
        - user
      summary: Add a new pet to the store.
      description: Add a new pet to the store.
      operationId: login
      requestBody:
        description: Create a new pet in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthTokens"
        '401':
          description: Incorrect password
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '404':
          description: Could not find user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      
components:
  schemas:
    LoginRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      xml:
        name: login_request
    AuthTokens:
      type: object
      properties:
        token:
          type: string
        refresh:
          type: string
      xml:
        name: login_request
    Error:
      type: string
      xml:
        name: error
    