openapi: 3.0.3
info:
  title: GoAuthService - OpenAPI 3.0
  description: |-
    This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.1
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:3000/
tags:
  - name: user
    description: Operations about user
paths:
  /login:
    post:
      tags:
        - user
      summary: Add a new pet to the store.
      description: Add a new pet to the store.
      operationId: login
      requestBody:
        description: Create a new pet in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
          application/xml:
            schema:
              $ref: '#/components/schemas/LoginRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/LoginRequest'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthTokens"
        '401':
          description: Incorrect password
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '404':
          description: Could not find user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      
components:
  schemas:
    LoginRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      xml:
        name: login_request
    AuthTokens:
      type: object
      properties:
        token:
          type: string
        refresh:
          type: string
      xml:
        name: login_request
    Error:
      type: string
      xml:
        name: error
    